name: 'fintech_data'
version: '1.0.0'
config-version: 2

# This must match the name in your profiles.yml exactly
profile: 'fintech_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  fintech_data:

    marts:
      +materialized: table

    staging:
      +materialized: view